import type { Metadata } from "next";
import localFont from "next/font/local";
import Provider from "./_provider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Flybasis",
  description: "Generated by create next app",
};

export default function RootLayout({  children, modal,}: Readonly<{  children: React.ReactNode;  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          {children}
          {modal}
        </Provider>
      </body>
    </html>
  );
}
