import type { Metadata } from "next";
import localFont from "next/font/local";
import Provider from "./_provider";
import "./globals.css";
import { Poppins } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Flybasis",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // Choose specific font weights
});
export default function RootLayout({  children, modal,}: Readonly<{  children: React.ReactNode;  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}

      >
        <Provider>
          {children}
          {modal}
        </Provider>
      </body>
    </html>
  );
}
